# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526e7b50e15628a7511d5ea01b6fa32936a9a369265e44b197523756f6eeaa0c05a13863734318778ea7222c040333a96ba8f74091b921d3a8e14d50058b301f

test:
  secret_key_base: dd1c5e818c3c26f232b63a891bfb310b1989edfa809dc9427fa6e24037f0a117555dd89f4dab64ea32fe3a96e8d7c560def04e76d52f8d02bb4743c6e16f05fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
